# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Clockworks
email: team@clockworks.io
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://clockworks.io" # the base hostname & protocol for your site

# Localization
languages: ['en', 'de']
exclude_from_localizations: ["js", "css", "assets", "blog", "_posts", "CNAME"]

# Build settings
markdown: kramdown

gems:
  - jekyll-multiple-languages-plugin

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
